name: Deploy Docs

on:
  push:
    branches: [shiror.ren]
  pull_request:
    branches: [shiror.ren]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: docs-deployer
  cancel-in-progress: true

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git config --global core.quotePath false
          git config --global core.ignorecase false
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: |
          bun ci
          bun run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: docs-dist
          folder: out
          clean: true
          single-commit: true
